name: Node CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: install teamspeak via docker
      run: |
        docker run -d --name=teamspeak\
          -p 10011:10011/tcp -p 10022:10022/tcp -p 30033:30033/tcp\
          -e TS3SERVER_LICENSE=accept -e TS3SERVER_QUERY_PROTOCOLS=raw,ssh\
          teamspeak ts3server serveradmin_password=abc123
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
        npm ci
    - name: run tests
      run: |
        npm test     
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
  deploy:
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Generate Docs
      run: |
        npm run generate-docs
    - name: Deploy on Github Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs